export const CREATE_SALON_REQUEST = "CREATE_SALON_REQUEST";
export const CREATE_SALON_SUCCESS = "CREATE_SALON_SUCCESS";
export const CREATE_SALON_FAILURE = "CREATE_SALON_FAILURE";

export const UPDATE_SALON_REQUEST = "UPDATE_SALON_REQUEST";
export const UPDATE_SALON_SUCCESS = "UPDATE_SALON_SUCCESS";
export const UPDATE_SALON_FAILURE = "UPDATE_SALON_FAILURE";

export const FETCH_SALON_REQUEST = "FETCH_SALON_REQUEST";
export const FETCH_SALON_SUCCESS = "FETCH_SALON_SUCCESS";
export const FETCH_SALON_FAILURE = "FETCH_SALON_FAILURE";

export const FETCH_SALON_BY_ID_REQUEST = "FETCH_SALON_BY_ID_REQUEST";
export const FETCH_SALON_BY_ID_SUCCESS = "FETCH_SALON_BY_ID_SUCCESS";
export const FETCH_SALON_BY_ID_FAILURE = "FETCH_SALON_BY_ID_FAILURE";

export const FETCH_SALON_BY_OWNER_REQUEST = "FETCH_SALON_BY_OWNER_REQUEST";
export const FETCH_SALON_BY_OWNER_SUCCESS = "FETCH_SALON_BY_OWNER_SUCCESS";
export const FETCH_SALON_BY_OWNER_FAILURE = "FETCH_SALON_BY_OWNER_FAILURE";

export const SEARCH_SALON_REQUEST = "SEARCH_SALON_REQUEST";
export const SEARCH_SALON_SUCCESS = "SEARCH_SALON_SUCCESS";
export const SEARCH_SALON_FAILURE = "SEARCH_SALON_FAILURE";